services:
  instance_builder:
    container_name: instance_builder
    image: ghcr.io/djoongaar/terraform
    command: bash
    tty: true
    volumes:
      - ./infra:/code/infra
      - ./ansible:/code/ansible
    environment:
      TF_VAR_instance_name: "newServer"
      TF_VAR_instance_type: "t2.micro"
      TF_VAR_zone: "us-east-1"
      TF_VAR_ami: "ami-00402f0bdf4996822"
      TF_VAR_vpc_id: "vpc-0e774d138be980966"
