#!/bin/bash


_check_server_state() {
  local counter=0
  local max_try=100

  echo -n "Checking instance: "

  while true
    do
      if
        [[ $(docker run --rm ghcr.io/djoongaar/terraform bash -c "aws ec2 describe-instance-status --instance-ids $1 | jq -r '.InstanceStatuses[0].InstanceState.Name'") == "running" ]] &&
        [[ $(docker run --rm ghcr.io/djoongaar/terraform bash -c "aws ec2 describe-instance-status --instance-ids $1 | jq -r '.InstanceStatuses[0].InstanceStatus.Status'") == "ok" ]] &&
        [[ $(docker run --rm ghcr.io/djoongaar/terraform bash -c "aws ec2 describe-instance-status --instance-ids $1 | jq -r '.InstanceStatuses[0].SystemStatus.Status'") == "ok" ]]; then
          break
      else
        if [ "$counter" -gt "$max_try" ]; then
          echo "[FAILED]"
          exit 1
        fi
        counter=$((counter+1))
        echo -n "."
        sleep 5
      fi
    done
  echo "[OK]"
}

_create_server() {
  docker run \
    --rm \
    --volume "./vpn:/code/vpn" \
    --env-file .env \
    ghcr.io/djoongaar/terraform \
    bash -c """
      cd vpn &&
      terraform init &&
      terraform fmt &&
      terraform validate &&
      terraform apply -auto-approve &&
      chmod 400 .ssh/id_rsa
    """

  # Saving instance configuration into json file
  rm -f vpn/instance.json &&
  docker run \
    --rm \
    --volume "./vpn:/code/vpn" \
    --env-file .env \
    ghcr.io/djoongaar/terraform \
    bash -c """
      cd vpn &&
      terraform output -json
    """ > vpn/instance.json

  # Creating inventory

  local instance_public_ip=$(cat vpn/instance.json | jq -r '.instance_public_ip.value')

  rm -f vpn/inventory.ini &&
  echo "[myhosts]" >> vpn/inventory.ini
  echo  "$instance_public_ip" >> vpn/inventory.ini
}

_install_openvpn() {
  local instance_id=$(cat vpn/instance.json | jq -r '.instance_id.value')

  _check_server_state "$instance_id"

  docker run \
    --rm \
    --volume "./vpn:/code/vpn" \
    --env-file .env \
    ghcr.io/djoongaar/terraform \
    bash -c "ansible-playbook -v -i vpn/inventory.ini vpn/openvpn.yml"
}

_destroy_server() {
  docker run \
    --rm \
    --volume "./vpn:/code/vpn" \
    --env-file .env \
    ghcr.io/djoongaar/terraform \
    bash -c """
      cd vpn &&
      terraform destroy -auto-approve
    """

  rm -f vpn/instance.json
  rm -f vpn/inventory.ini
  rm -rf vpn/.ssh
}

_validate_client_name() {
  local client_name="$1"

  if
    [[ ${#client_name} -gt 2 ]] &&
    [[ "$client_name" =~ ^[0-9a-zA-Z]+$ ]]; then
    echo "client_name: $client_name"
  else
    echo """
      Client name is not valid!
      The name must be at least 3 characters long.
      The name must contain only alphanumeric characters.
      """
    exit 1
  fi
}

_add_client() {
  local client_name="$1"
  local instance_id=$(cat vpn/instance.json | jq -r '.instance_id.value')
  local instance_public_ip=$(cat vpn/instance.json | jq -r '.instance_public_ip.value')

  _validate_client_name "$client_name"
  _check_server_state "$instance_id"

  docker run \
    --rm \
    --volume "./vpn:/code/vpn" \
    ghcr.io/djoongaar/terraform \
    bash -c "ansible-playbook -v -i vpn/inventory.ini vpn/add_client.yml -e \"new_client=$client_name\""

  docker run \
    --rm \
    --volume "./vpn:/code/vpn" \
    --env-file .env \
    ghcr.io/djoongaar/terraform \
    bash -c "scp -i vpn/.ssh/id_rsa $instance_public_ip:~/client-configs/files/$client_name.ovpn vpn/$client_name.ovpn"
}

if [ "$1" = "--create" ]; then
  ### Build an instance by terraform
	_create_server
	### Install and configure OpenVPN Server, PKI
  _install_openvpn
  ### Create admin configuration
  _add_client "admin"
elif [ "$1" = "--destroy" ]; then
  _destroy_server
elif [ "$1" = "--add-client" ]; then
  if [ -z $2 ]; then
    echo "You should provide client name"
  else
    # TODO: Вот тут нужно доабвить валидацию имени:
    # TODO: Приводить имя клиента к нижнему регистру
    # TODO: Имя должно быть уникально
    _add_client "$2"
  fi
fi