- name: Install OpenVPN Server
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: I am alive

    - name: Whoami
      ansible.builtin.shell:
        cmd: whoami

    - name: Update apt
      ansible.builtin.shell:
        cmd: sudo apt update

    - name: Install openvpn and easy-rsa
      ansible.builtin.shell:
        cmd: sudo apt install -y openvpn easy-rsa

    - name: Create easy-rsa directory
      ansible.builtin.file:
        path: ~/easy-rsa
        state: directory
        mode: '0700'
        owner: admin
        group: admin

    - name: Create a symbolic link
      ansible.builtin.shell:
        cmd: ln -fs /usr/share/easy-rsa/* ~/easy-rsa/

    - name: Setting vars
      ansible.builtin.shell: |
        rm -f ~/easy-rsa/vars
        touch ~/easy-rsa/vars
        echo "set_var EASYRSA_REQ_COUNTRY    \"US\""                       >> ~/easy-rsa/vars
        echo "set_var EASYRSA_REQ_PROVINCE   \"NewYork\""                  >> ~/easy-rsa/vars
        echo "set_var EASYRSA_REQ_CITY       \"New York City\""            >> ~/easy-rsa/vars
        echo "set_var EASYRSA_REQ_ORG        \"DigitalOcean\""             >> ~/easy-rsa/vars
        echo "set_var EASYRSA_REQ_EMAIL      \"ipsharaev@gmail.com\""      >> ~/easy-rsa/vars
        echo "set_var EASYRSA_REQ_OU         \"Community\""                >> ~/easy-rsa/vars
        echo "set_var EASYRSA_ALGO           \"ec\""                       >> ~/easy-rsa/vars
        echo "set_var EASYRSA_DIGEST         \"sha512\""                   >> ~/easy-rsa/vars

    - name: Generate PKI
      ansible.builtin.shell: |
        cd ~/easy-rsa
        ./easyrsa --batch init-pki

    - name: Generate OpenVPN Certificate Request
      ansible.builtin.shell: |
        cd ~/easy-rsa
        ./easyrsa --batch gen-req server nopass
        sudo cp ~/easy-rsa/pki/private/server.key /etc/openvpn/server/

    - name: Building CA
      ansible.builtin.shell: |
        cd ~/easy-rsa
        ./easyrsa --batch build-ca nopass

    - name: Signing the OpenVPN Certificate Request
      ansible.builtin.shell: |
        cd ~/easy-rsa
        ./easyrsa --batch sign-req server server
        sudo cp ~/easy-rsa/pki/ca.crt /etc/openvpn/server/ca.crt
        sudo cp ~/easy-rsa/pki/issued/server.crt /etc/openvpn/server/server.crt

    - name: Generate OpenVPN TLS-crypt key
      ansible.builtin.shell: |
        cd ~/easy-rsa
        /usr/sbin/openvpn --genkey --secret ta.key
        sudo cp ta.key /etc/openvpn/server

    - name: Create Client Config
      ansible.builtin.shell: |
        mkdir -p ~/client-config/keys
        chmod -R 700 ~/client-configs

    - name: Add Certificate for Admin
      ansible.builtin.shell: |
        cd ~/easy-rsa
        ./easyrsa --batch gen-req admin nopass
        cp pki/private/admin.key ~/client-config/keys/
        ./easyrsa --batch sign-req client admin
        cp pki/issued/admin.crt ~/client-config/keys/
        cp ~/easy-rsa/pki/ca.crt ~/client-config/keys/
        cp ta.key ~/client-config/keys/

    - name: Configure OpenVPN server
      ansible.builtin.shell: |
        sudo cp /usr/share/doc/openvpn/examples/sample-config-files/server.conf ~/server.conf
        sed -i "/^tls-auth ta.key 0/c\; tls-auth ta.key 0" ~/server.conf
        sed -i "/^cipher AES-256-CBC/c\; cipher AES-256-CBC" ~/server.conf
        sed -i "/^dh dh2048.pem/c\; dh dh2048.pem" ~/server.conf
        sed -i "/^;push \"dhcp-option DNS 208.67.222.222\"/c\push \"dhcp-option DNS 208.67.222.222\"" ~/server.conf
        sed -i "/^;push \"dhcp-option DNS 208.67.220.220\"/c\push \"dhcp-option DNS 208.67.220.220\"" ~/server.conf
        echo -e "\n" >> ~/server.conf
        echo "dh none" >> ~/server.conf
        echo "tls-crypt ta.key" >> ~/server.conf
        echo "cipher AES-256-GCM" >> ~/server.conf
        echo "auth SHA256" >> ~/server.conf
        echo "user nobody" >> ~/server.conf
        echo "group nogroup" >> ~/server.conf
        echo "push \"redirect-gateway def1 bypass-dhcp\"" >> ~/server.conf
        sudo cp ~/server.conf /etc/openvpn/server/