- name: Install and Configure PostgreSQL
  hosts: myhosts
  vars:
    ansible_ssh_private_key_file: "postgres/.ssh/id_rsa"
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Repository configuration
      ansible.builtin.shell: |
        sudo apt -y install curl ca-certificates
        sudo install -d /usr/share/postgresql-common/pgdg
        sudo curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
        sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

    - name: Install PostgreSQL 15 server
      ansible.builtin.shell: |
        sudo apt update && sudo apt -y install postgresql-15